default = { worlds = [{ reference = "ghcr.io/fermyon/akamai-functions/wit:1.0.0", world = "akamai:functions/platform@1.0.0" }] }

[triggers]

[triggers.http]
worlds = [
  {reference = "ghcr.io/fermyon/akamai-functions/wit:1.0.0", world = "akamai:functions/http-trigger@1.0.0"},
  {reference = "ghcr.io/fermyon/akamai-functions/wit:1.0.0", world = "akamai:functions/http-trigger-rc20231018@1.0.0"},
  {reference = "ghcr.io/fermyon/akamai-functions/wit:1.0.0", world = "akamai:functions/http-trigger-rc20231110@1.0.0"},
  {reference = "ghcr.io/fermyon/akamai-functions/wit:1.0.0", world = "akamai:functions/http-trigger-legacy@1.0.0"}
]

[metadata]
plugins = ["aka"]

[metadata.templates]
url = "https://github.com/akamai-developers/akamai-functions-spin-templates"
tag = "v1.0.0"
